[features]
seeds = false
[programs.devnet]
staking = "FvSyVqCPvwVJ8XyNVLb3h4vUV36nr8c26CpF6YyL8zUu"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/tomekregulski/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
